console.log("Hello World");
console.log("Welcome to JavaScript");
var num = 10;
console.log(num);
console.log(typeof(num));
num = "Hello";
console.log(num);
console.log(typeof(num));
num = true;
console.log(num);
console.log(typeof(num));
num = null;
console.log(num);
console.log(typeof(num));
num = undefined;
console.log(num);
console.log(typeof(num));